name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

env:
  PYTHON_VERSION: "3.10"
  TERRAFORM_DOCS_VERSION: "v0.16.0"
  TFLINT_VERSION: "v0.40.1"

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    - name: python lib cache
      uses: actions/cache@v3
      with:
        path: {{ .env.LD_LIBRARY_PATH }}/lib/python${{ env.PYTHON_VERSION }}/site-packages
        key: ${{ runner.os }}-python-lib-${{ hashFiles('**/requirements.txt') }}

    - name: python lib scripts
      uses: actions/cache@v3
      with:
        path: {{ .env.LD_LIBRARY_PATH }}/Scripts
        key: ${{ runner.os }}-python-scripts-${{ hashFiles('**/requirements.txt') }}

    - run: pip install -r requirements.txt

    - name: TFLint cache
      uses: actions/cache@v3
      with:
        path: ~/.tflint.d/plugins
        key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      with:
        tflint_version: ${{ env.TFLINT_VERSION }}

    - uses: lablabs/setup-terraform-docs@v1.0.4
      with:
        terraform_docs_version: ${{ env.TERRAFORM_DOCS_VERSION }}

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
