name: pre-commit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

env:
  PYTHON_VERSION: "3.10"
  TERRAFORM_DOCS_VERSION: "v0.16.0"
  TFLINT_VERSION: "v0.40.1"

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    - name: Python lib cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}/lib/python${{ env.PYTHON_VERSION }}/site-packages
        key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-lib-${{ hashFiles('**/requirements.txt') }}

    - name: Install checkov
      run: pip install -r requirements.txt

    - name: TFLint cache
      uses: actions/cache@v3
      with:
        path: ~/.tflint.d/plugins
        key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Install TFLint
      uses: terraform-linters/setup-tflint@v2
      with:
        tflint_version: ${{ env.TFLINT_VERSION }}

    - name: Install terraform-docs
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo: terraform-docs/terraform-docs
        tag: ${{ env.TERRAFORM_DOCS_VERSION }}
        cache: enable

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
